#!/usr/bin/env bash
# Mechanical client-matrix runner (round-34 ruling 7).
#
# Every number that appears in the evidence MUST come out of this script.
# It runs the whole required client matrix against ONE index.html, captures
# the raw stdout+stderr of each suite, checks each suite's EXIT STATUS, and
# writes a TOTALS file that is generated from completed runner output only.
# Nothing here anticipates a result; a suite that is killed by the timeout or
# that exits non-zero is reported as such and poisons the overall verdict.
#
#   usage: tests/browser/run-client-matrix.sh <output-dir> [per-suite-timeout-seconds]
#
# ARTIFACT-SCOPE NOTE: c11m8-recovery is deliberately NOT in this matrix. It
# requires the SYNC_SAFE recovery artifact as CF_SRC, not index.html.

set -u
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${1:-}"
TMO="${2:-1200}"
if [ -z "$OUT" ]; then
  echo "usage: $0 <output-dir> [per-suite-timeout-seconds]" >&2; exit 64
fi
mkdir -p "$OUT/raw" || exit 65

SRC="$REPO/index.html"
HASH="$(sha256sum "$SRC" | awk '{print $1}')"
STARTED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

SUITES="
c15m10-lease
c16m10-core
c17m10-displaced
c18m10-photoq
c19m10-gate
c11m8-accounts
c11m8-faults
c11m8-matrix
c11m8-quota
c11m8-replay
c11m8-tags
c11m8-upgrade
c14-correctness-fixes
"

ROWS="$OUT/.rows.$$"
: > "$ROWS"

for s in $SUITES; do
  f="$REPO/tests/browser/$s.browser.test.js"
  raw="$OUT/raw/$s.txt"
  if [ ! -f "$f" ]; then
    echo "MISSING $s" >&2
    printf '%s\tMISSING\t-\t-\t-\n' "$s" >> "$ROWS"
    continue
  fi
  echo "=== running $s (timeout ${TMO}s) ..." >&2
  t0=$(date +%s)
  ( cd "$REPO" && CF_SRC="$SRC" timeout -k 20 "$TMO" node "$f" ) > "$raw" 2>&1
  rc=$?
  t1=$(date +%s)
  # counts are read back OUT of the completed raw file, never anticipated
  p=$(grep -c '  ✓ ' "$raw")
  x=$(grep -c '  ✗ ' "$raw")
  if [ "$rc" -eq 0 ]; then verdict=PASS
  elif [ "$rc" -eq 124 ] || [ "$rc" -eq 137 ]; then verdict=TIMEOUT
  else verdict=FAIL
  fi
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$s" "$verdict" "$rc" "$p" "$x" "$((t1-t0))" >> "$ROWS"
  echo "    $s -> $verdict (exit $rc, $p passed, $x failed, $((t1-t0))s)" >&2
done

TOT="$OUT/TOTALS.txt"
{
  echo "CLIENT MATRIX — mechanically generated by tests/browser/run-client-matrix.sh"
  echo "started (UTC):    $STARTED"
  echo "finished (UTC):   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "CF_SRC:           $SRC"
  echo "index.html sha256 $HASH"
  echo "per-suite timeout ${TMO}s   (exit 124/137 => TIMEOUT)"
  echo "raw output:       $OUT/raw/<suite>.txt   (one file per suite, stdout+stderr)"
  echo
  printf '%-24s %-8s %-6s %-8s %-8s %s\n' SUITE VERDICT EXIT PASSED FAILED SECS
  printf '%-24s %-8s %-6s %-8s %-8s %s\n' ------------------------ -------- ------ -------- -------- ----
  tp=0; tf=0; bad=0; nsuite=0
  while IFS=$'\t' read -r s v rc p x secs; do
    printf '%-24s %-8s %-6s %-8s %-8s %s\n' "$s" "$v" "$rc" "$p" "$x" "$secs"
    nsuite=$((nsuite+1))
    case "$p" in ''|*[!0-9]*) ;; *) tp=$((tp+p)) ;; esac
    case "$x" in ''|*[!0-9]*) ;; *) tf=$((tf+x)) ;; esac
    [ "$v" = "PASS" ] || bad=$((bad+1))
  done < "$ROWS"
  echo
  echo "suites run:            $nsuite"
  echo "suites not PASS:       $bad"
  echo "assertions passed:     $tp"
  echo "assertions failed:     $tf"
  echo
  if [ "$bad" -eq 0 ] && [ "$tf" -eq 0 ]; then
    echo "VERDICT: GREEN — every suite exited 0 with zero failed assertions."
  else
    echo "VERDICT: NOT GREEN — see the rows above and the raw files."
  fi
} > "$TOT"

rm -f "$ROWS"
cat "$TOT"
grep -q '^VERDICT: GREEN' "$TOT" && exit 0
exit 1
