/* ============================================================
   PocketBase adapter  (generated by tools/pb-port.mjs)
   Replaces the GitHub Contents API sync with a self-hosted
   PocketBase backend: real accounts, hard per-user isolation.
   ============================================================ */
var PB_DEFAULT_BASE="https://rack.tail6fa16c.ts.net";
var PB_KEY="wl_pb";
/* "Remember me" decides WHERE the session lives, not whether one exists:
   localStorage survives closing the app; sessionStorage dies with the tab. Reads
   check session first so an un-remembered login always wins over a stale one. */
function pbCfg(){
  try{var s=sessionStorage.getItem(PB_KEY);if(s)return JSON.parse(s)||{};}catch(e){}
  try{return JSON.parse(localStorage.getItem(PB_KEY))||{};}catch(e){return {};}}
function setPbCfg(c){
  try{
    if(c&&c.remember===false){sessionStorage.setItem(PB_KEY,JSON.stringify(c));localStorage.removeItem(PB_KEY);}
    else{localStorage.setItem(PB_KEY,JSON.stringify(c));try{sessionStorage.removeItem(PB_KEY);}catch(e){}}
  }catch(e){}}
function pbBase(){var c=pbCfg();return String(c.base||PB_DEFAULT_BASE).replace(/\/+$/,"");}
function pbTok(){return pbCfg().token||"";}
function pbUid(){return pbCfg().uid||"";}
function pbEmail(){return pbCfg().email||"";}
function pbHeaders(json){var h={};var t=pbTok();if(t)h.Authorization=t;if(json)h["Content-Type"]="application/json";return h;}

/* the app asks "is sync configured?" everywhere — now it means "logged in" */
function syncOn(){return !!(pbTok()&&pbUid());}

/* ---- GitHub is retired ----
   A lot of GitHub code survives as unreachable leftovers, but "unreachable" is a
   claim that rots. Make it structurally true instead: the old config is now
   permanently empty, so no surviving path can ever produce an Authorization header,
   and the stored Personal Access Token is deleted from this device — it is a real
   credential sitting in localStorage with nothing left that should use it. */
function syncCfg(){return {};}
function setSyncCfg(){}
try{localStorage.removeItem(SYNC_KEY);}catch(e){}

/* Weekly regenerate had no shipping UI; the scheduled run covers it. */
function genSummary(){toast("Coach Max writes your check-in on your own server now.");}

/* "Complete today" — part of the daily ritual: finish logging, tap, read the recap.
   It used to dispatch a GitHub Actions run; now it sets a request flag on the record
   that the Synology coach picks up on its next polling pass, then watches for the
   recap to appear. Latency = polling interval + ~10s of generation. */
function genNightly(){
  if(!syncOn()){toast("Log in first");return;}
  if(state.nightBusy||state.genBusy)return;
  var sel=state.selDate;
  var miss=dayMissing(sel);
  if(miss.length){toast("Log "+miss.join(", ")+" first to complete "+(sel===todayISO()?"today":"this day"));return;}
  state.nightBusy=true;render();
  var prevGen=(coachNightly(sel)&&coachNightly(sel).generated)||null;
  pushDataPromise().then(function(){
    return new Promise(function(res,rej){
      pbSave({coachreq:{day:sel,ts:Date.now()}},function(ok){ok?res():rej(new Error("Couldn't reach your server"));});});
  }).then(function(){
    /* poll the REPORTS SERVICE for the recap: a pure read, no synced state,
       no revision, nothing to conflict with (Owner architecture, 2026-08-04).
       Previously this pbGetRecord+applyCloud'd the whole record, which
       overwrote local state without advancing the sync base — the same
       latent hazard the weekly path hit. */
    return new Promise(function(resolve){
      var n=0,MAX=70;
      function tick(){n++;
        fetchCoachReports(function(){
          var got=(state.coachRpt&&state.coachRpt.nightly&&state.coachRpt.nightly[sel])||null;
          if(got&&got.text&&got.generated!==prevGen){resolve(true);return;}
          if(n>=MAX){resolve(null);return;}
          setTimeout(tick,6000);});}
      setTimeout(tick,8000);});
  }).then(function(d){
    state.nightBusy=false;
    if(d){
      state.settings.seenNightly=sel;save();
      state.nightOpen=true;
      toast((sel===todayISO()?"Today":"That day")+"’s recap is ready");
    }else toast("Still working — it will appear here shortly");
    render();
  }).catch(function(e){state.nightBusy=false;render();toast(e.message||"Couldn’t generate");});}

/* every account owns its own data, so the old multi-profile uid tagging is moot */
function myUid(){return "owner";}
function isOwner(){return true;}
/* connections/invite feature fully retired (.460) — stubs AND callers removed together */

/* ---- auth ---- */
function pbLogin(email,password,cb,remember){
  var base=pbBase();
  fetch(base+"/api/collections/users/auth-with-password",{method:"POST",headers:{"Content-Type":"application/json"},
    body:JSON.stringify({identity:email,password:password})})
    .then(function(r){if(r.status===400)return Promise.reject("bad");if(!r.ok)return Promise.reject("error");return r.json();})
    .then(function(j){var c=pbCfg();c.base=base;c.token=j.token;c.uid=j.record.id;c.email=j.record.email;
      if(remember!==undefined)c.remember=!!remember;
      setPbCfg(c);cb&&cb(true);})
    .catch(function(e){cb&&cb(false,(e==="bad")?"bad":(e==="error")?"error":"offline");});}

/* PocketBase requires the CURRENT password to change it (min 8 chars for the new
   one). Other devices' existing tokens can still READ afterwards, but auth-refresh
   returns 401 — and since the app refreshes on every open, they are effectively
   signed out and will need the new password. */
function pbChangePassword(oldPw,newPw,confirmPw,cb){
  if(!oldPw||!newPw){cb(false,"Fill in every field.");return;}
  if(newPw.length<8){cb(false,"New password must be at least 8 characters.");return;}
  if(newPw!==confirmPw){cb(false,"The new passwords don’t match.");return;}
  if(newPw===oldPw){cb(false,"That’s the same as your current password.");return;}
  fetch(pbBase()+"/api/collections/users/records/"+pbUid(),{method:"PATCH",headers:pbHeaders(true),
    body:JSON.stringify({oldPassword:oldPw,password:newPw,passwordConfirm:confirmPw})})
    .then(function(r){return r.json().then(function(j){return r.ok?j:Promise.reject(j);});})
    .then(function(){
      /* re-authenticate so this device keeps a token minted against the new password */
      var c=pbCfg();
      pbLogin(pbEmail(),newPw,function(ok){cb(true,ok?null:"Password changed — please log in again.");},c.remember!==false);})
    .catch(function(j){
      var msg="Couldn’t change your password.";
      if(j&&j.data&&j.data.oldPassword)msg="Your current password isn’t right.";
      else if(j&&j.data&&j.data.password&&j.data.password.message)msg=j.data.password.message;
      else if(!j||!j.data)msg="Can’t reach the server. Is Tailscale on?";
      cb(false,msg);});}

/* silently extend the session on every open so a 90-day token never lapses mid-use */
function pbRefresh(cb){
  if(!syncOn()){cb&&cb(false);return;}
  fetch(pbBase()+"/api/collections/users/auth-refresh",{method:"POST",headers:pbHeaders(true)})
    .then(function(r){if(r.status===401||r.status===403)return Promise.reject("auth");if(!r.ok)return Promise.reject("error");return r.json();})
    .then(function(j){var c=pbCfg();c.token=j.token;c.uid=j.record.id;c.email=j.record.email;setPbCfg(c);cb&&cb(true);})
    .catch(function(e){
      if(e==="auth"){
        /* the session is dead (most often: the password was changed on another
           device). Drop the token but KEEP local data, and say why — the app
           otherwise appears signed in and then abruptly boots you. */
        pbClearSession(true);
        pbLoginState.err="Your session ended — that usually means the password was changed on another device. Please sign in again.";
        try{render();}catch(_e){}
      }
      cb&&cb(false);});}

/* Clears ONLY the session. Local data survives, so a session that expires or gets
   invalidated (e.g. the password was changed on another device) can never destroy
   changes this device hadn't uploaded yet. */
function pbClearSession(keepEmail){
  try{m10Reset("session-cleared");}catch(e){}/* M10 wiring (K2) */
  var c=pbCfg(),keep={};
  /* keep the server URL — it is configuration, not session. Dropping it silently
     reverts a custom server to the compiled-in default on any expiry. */
  if(c.base)keep.base=c.base;
  if(c.remember!==undefined)keep.remember=c.remember;
  if(keepEmail&&c.email)keep.email=c.email;   /* pre-fill the login form again */
  try{localStorage.removeItem(PB_KEY);}catch(e){}
  try{sessionStorage.removeItem(PB_KEY);}catch(e){}
  try{if(keep.base||keep.email)localStorage.setItem(PB_KEY,JSON.stringify(keep));}catch(e){}
  pbRecId=null;}

/* Full logout: session AND this device's cached copy. Only for an explicit "Log out",
   where wiping is the point — a shared iPad must not leak the previous account, so
   the email is dropped too. */
var LOGOUT_JOURNAL_KEY="wl_logout_journal",LOGOUT_JOURNAL_V=1;
/* localStorage has no transaction, and a logout also has to clear a session that
   lives in a DIFFERENT store -- so genuine atomicity is not available. What is
   available is an honest record of how far the wipe got, so that an interrupted
   one is never resolved by guessing.

   Product Owner ruling 2026-08-01: when the app cannot tell whether a logout
   reached the committed state, it STOPS AND ASKS. It does not restore health
   data onto a device the athlete deliberately logged out of, and it does not
   finish destroying data they may not have exported. */
var logoutRecovery=null;   /* null, or {phase, journal} while a wipe is unresolved */
function logoutRecoveryPending(){return !!logoutRecovery;}
function logoutTargets(){return [KEY,TKEY,WOKEY,DIRTY_KEY,LAST_KEY,LASTOWNER_KEY,TRECOVERY_KEY];}
var LOGOUT_PHASES=["prepared","wiping","data-cleared","committed"];

function readSessionPair(){
  var out={local:null,session:null};
  try{out.local=localStorage.getItem(PB_KEY);}catch(e){}
  try{out.session=sessionStorage.getItem(PB_KEY);}catch(e){}
  return out;}

/* Exactly the approved keys, exactly the expected value types. restore() never
   iterates keys supplied by the file -- only the fixed target list -- so a
   tampered or corrupt journal cannot write anywhere it likes. */
function validLogoutJournal(j){
  if(!j||typeof j!=="object"||Array.isArray(j))return false;
  if(j.v!==LOGOUT_JOURNAL_V)return false;
  if(typeof j.account!=="string")return false;
  if(typeof j.appBuild!=="string"||!j.appBuild)return false;
  if(LOGOUT_PHASES.indexOf(j.phase)<0)return false;
  if(!j.vals||typeof j.vals!=="object"||Array.isArray(j.vals))return false;
  var want=logoutTargets(),i;
  if(Object.keys(j.vals).length!==want.length)return false;
  for(i=0;i<want.length;i++){
    if(!(want[i] in j.vals))return false;
    var v=j.vals[want[i]];
    if(!(v===null||typeof v==="string"))return false;}
  if(!j.session||typeof j.session!=="object")return false;
  if(!(j.session.local===null||typeof j.session.local==="string"))return false;
  if(!(j.session.session===null||typeof j.session.session==="string"))return false;
  return true;}

function readLogoutJournal(){
  var raw=null;
  try{raw=localStorage.getItem(LOGOUT_JOURNAL_KEY);}catch(e){return {status:"unreadable",j:null};}
  if(raw===null)return {status:"absent",j:null};
  var j=null;try{j=JSON.parse(raw);}catch(e){return {status:"invalid",j:null};}
  if(!validLogoutJournal(j))return {status:"invalid",j:null};
  return {status:"valid",j:j};}

function writeLogoutJournalPhase(j,phase){
  j.phase=phase;
  var str;
  try{str=JSON.stringify(j);}catch(e){return false;}
  try{localStorage.setItem(LOGOUT_JOURNAL_KEY,str);}catch(e){return false;}
  var back=null;
  try{back=localStorage.getItem(LOGOUT_JOURNAL_KEY);}catch(e){return false;}
  return back===str;}

function buildLogoutJournal(){
  var j={v:LOGOUT_JOURNAL_V,at:todayISO(),account:recoveryAccountId(),appBuild:APP_BUILD,
         phase:"prepared",vals:{},session:readSessionPair()};
  var ks=logoutTargets(),i;
  for(i=0;i<ks.length;i++){
    var v=null;
    try{v=localStorage.getItem(ks[i]);}catch(e){return null;}
    j.vals[ks[i]]=v;}
  return j;}

/* Restores the fixed target list AND both session stores, then verifies each. */
function restoreFromJournal(j){
  var ok=true,ks=logoutTargets(),i;
  for(i=0;i<ks.length;i++){
    var k=ks[i],want=j.vals[k];
    try{if(want===null)localStorage.removeItem(k);else localStorage.setItem(k,want);}catch(e){ok=false;continue;}
    var back=null;
    try{back=localStorage.getItem(k);}catch(e){ok=false;continue;}
    if(back!==want)ok=false;}
  [["local",localStorage],["session",typeof sessionStorage!=="undefined"?sessionStorage:null]].forEach(function(pair){
    var want=j.session[pair[0]],store=pair[1];
    if(!store)return;
    try{if(want===null)store.removeItem(PB_KEY);else store.setItem(PB_KEY,want);}catch(e){ok=false;return;}
    var back=null;
    try{back=store.getItem(PB_KEY);}catch(e){ok=false;return;}
    if(back!==want)ok=false;});
  return ok;}

function deleteLogoutJournalVerified(){
  try{localStorage.removeItem(LOGOUT_JOURNAL_KEY);}catch(e){return false;}
  var back=null;
  try{back=localStorage.getItem(LOGOUT_JOURNAL_KEY);}catch(e){return false;}
  return back===null;}

/* Boot gate. ANY surviving or unreadable journal stops the app before it loads
   user data or touches the network. Only the "prepared" phase is self-evidently
   safe: nothing had been removed yet, so the journal is simply discarded. */
function checkLogoutJournal(){
  var r=readLogoutJournal();
  if(r.status==="absent")return true;
  if(r.status==="valid"&&r.j.phase==="prepared"){
    if(deleteLogoutJournalVerified())return true;
    logoutRecovery={phase:"prepared",journal:r.j};return false;}
  logoutRecovery={phase:(r.status==="valid"?r.j.phase:"unreadable"),journal:(r.status==="valid"?r.j:null)};
  return false;}

/* The two answers the athlete can give. Neither is taken automatically. */
function logoutRecoveryRestore(){
  var j=logoutRecovery&&logoutRecovery.journal;
  if(!j){toast("That recovery record can't be read — nothing was changed");return false;}
  if(!restoreFromJournal(j)){toast("Couldn't fully restore — nothing else was changed");return false;}
  if(!deleteLogoutJournalVerified()){toast("Restored, but the recovery record could not be cleared");return false;}
  logoutRecovery=null;location.reload();return true;}
function logoutRecoveryFinish(){
  /* Product Owner ruling 2026-08-01: an UNREADABLE journal offers no destructive
     escape at all. The app cannot know what it would be erasing, so it stays
     locked and the bytes stay put until the reviewed recovery procedure. */
  if(!(logoutRecovery&&logoutRecovery.journal)){
    toast("This can't be erased from here — the record of the log-out can't be read");
    return false;}
  var ks=logoutTargets(),i;
  for(i=0;i<ks.length;i++){try{localStorage.removeItem(ks[i]);}catch(e){toast("Couldn't finish clearing this device — nothing more was changed");return false;}}
  /* Postcondition, verified: every target key absent, BOTH session slots absent
     entirely (not merely token-free -- ruling 8), and the journal gone. */
  for(i=0;i<ks.length;i++){
    var still=null;
    try{still=localStorage.getItem(ks[i]);}catch(e){toast("Couldn't verify this device was cleared");return false;}
    if(still!==null){toast("Couldn't finish clearing this device");return false;}}
  try{pbClearSession(false);}catch(e){}
  try{sessionStorage.removeItem(PB_KEY);}catch(e){}
  /* Same postcondition as an ordinary logout: pbClearSession legitimately keeps
     the server URL (configuration, not session) in the localStorage slot, so
     that slot is checked for CREDENTIALS; sessionStorage must be entirely empty
     of the key. */
  var lraw2=null;
  try{lraw2=localStorage.getItem(PB_KEY);}catch(e){toast("Couldn't verify the session was cleared");return false;}
  if(lraw2!==null){
    var lc2=null;try{lc2=JSON.parse(lraw2);}catch(e){toast("Couldn't clear the session");return false;}
    if(lc2&&(lc2.token||lc2.uid||lc2.email)){toast("Couldn't clear the session");return false;}}
  try{if(sessionStorage.getItem(PB_KEY)!==null){toast("Couldn't clear the session");return false;}}
  catch(e){toast("Couldn't verify the session was cleared");return false;}
  if(!deleteLogoutJournalVerified()){toast("Couldn't clear the recovery record");return false;}
  logoutRecovery=null;location.reload();return true;}

function pbForceLogout(){
  if(ownershipAmbiguous()){
    toast("Can't log out yet — this device holds data from another account");
    return false;}
  var j=buildLogoutJournal();
  if(!j||!writeLogoutJournalPhase(j,"prepared")){
    toast("Couldn't prepare a safe log-out on this device — nothing was removed");
    return false;}

  function rollback(msg){
    if(restoreFromJournal(j)&&deleteLogoutJournalVerified()){
      toast(msg+" — every value was put back exactly as it was");
    }else{
      logoutRecovery={phase:j.phase,journal:j};
      toast(msg+". This device now needs a decision before it can be used.");}
    return false;}

  if(!writeLogoutJournalPhase(j,"wiping"))return rollback("Couldn't record the log-out safely");

  var acct=recoveryAccountId();
  if(!clearTrainingRecovery(acct))return rollback("Couldn't clear this device's saved training copy");

  var targets=logoutTargets(),i;
  for(i=0;i<targets.length;i++){
    try{localStorage.removeItem(targets[i]);}catch(e){return rollback("Couldn't clear this device");}}
  for(i=0;i<targets.length;i++){
    var still=null;
    try{still=localStorage.getItem(targets[i]);}catch(e){return rollback("Couldn't verify this device was cleared");}
    if(still!==null)return rollback("Couldn't clear this device");}

  if(!writeLogoutJournalPhase(j,"data-cleared"))return rollback("Couldn't record the log-out safely");

  pbClearSession(false);
  try{sessionStorage.removeItem(PB_KEY);}catch(e){}
  /* The privacy postcondition is ABSENCE of wl_pb in both stores, not merely the
     absence of a parseable token: malformed session bytes are still session
     bytes. pbClearSession keeps base/remember in localStorage by design, so that
     slot is checked for credentials only after re-writing; sessionStorage must be
     entirely empty of the key. */
  var leftover=false;
  var lraw=null;try{lraw=localStorage.getItem(PB_KEY);}catch(e){leftover=true;}
  if(lraw!==null&&lraw!==undefined&&lraw!==""){
    var lc=null;try{lc=JSON.parse(lraw);}catch(e){leftover=true;}
    if(lc&&(lc.token||lc.uid||lc.email))leftover=true;}
  try{if(sessionStorage.getItem(PB_KEY)!==null)leftover=true;}catch(e){leftover=true;}
  if(leftover)return rollback("Couldn't clear the session");

  if(!writeLogoutJournalPhase(j,"committed")){
    /* The wipe is done and the session is gone; only the record of it failed.
       Leave it: boot will stop and ask rather than silently undo a completed
       logout or silently keep a copy of the data. */
    logoutRecovery={phase:"committed",journal:j};
    toast("Logged out, but this device needs a decision before it can be used again.");
    return false;}
  /* Verified deletion. A surviving journal holds a complete copy of the health
     data this logout just erased, so an unverified removeItem is not enough. */
  if(!deleteLogoutJournalVerified()){
    logoutRecovery={phase:"committed",journal:j};
    toast("Logged out, but a copy of the cleared data is still on this device.");
    return false;}
  return true;}
function pbLogout(){
  askConfirm("Log out on this device? Your data stays safe on the server — log back in any time.",function(){
    if(pbForceLogout())location.reload();   /* a refused logout must not reload away its own error */
  },{label:"Log out",danger:true});}

/* ---- the single appdata record ---- */
var pbRecId=null;
function pbGetRecord(cb){
  if(ownershipAmbiguous()){cb&&cb(null,"ambiguous");return;}
  if(!syncOn()){cb&&cb(null,"not configured");return;}
  fetch(pbBase()+"/api/collections/appdata/records?perPage=1&filter="+encodeURIComponent('user="'+pbUid()+'"')+"&t="+Date.now(),
    {headers:pbHeaders(),cache:"no-store"})
    .then(function(r){if(r.status===401||r.status===403)return Promise.reject("auth");if(!r.ok)return Promise.reject("error");return r.json();})
    .then(function(p){var rec=(p.items&&p.items[0])||null;if(rec)pbRecId=rec.id;cb&&cb(rec,null);})
    .catch(function(e){cb&&cb(null,(e==="auth")?"auth":(e==="error")?"error":"offline");});}

function pbSave(fields,cb){
  /* Enforced at the primitive, not at named callers. pbSave has call sites in
     the HealthKit import, the coach request, the nightly generator and
     pushDataPromise() as well as cloudPush/trainingPush; gating those by name
     would leave whichever one is added next unprotected. */
  if(ownershipAmbiguous()){cb&&cb(false,"ambiguous");return;}
  if(!syncOn()){cb&&cb(false,"not configured");return;}
  var base=pbBase();
  function write(id){
    var url=base+"/api/collections/appdata/records"+(id?("/"+id):"");
    var body=id?fields:Object.assign({user:pbUid()},fields);
    return fetch(url,{method:id?"PATCH":"POST",headers:pbHeaders(true),body:JSON.stringify(body)})
      .then(function(r){
        if(r.status===401||r.status===403)return Promise.reject("auth");
        if(r.status===404&&id){pbRecId=null;return Promise.reject("gone");}
        if(!r.ok)return Promise.reject("error");
        return r.json();});}
  var run=pbRecId?write(pbRecId):new Promise(function(res,rej){
    pbGetRecord(function(rec,err){if(err)return rej(err);write(rec?rec.id:null).then(res,rej);});});
  run.then(function(j){if(j&&j.id)pbRecId=j.id;cb&&cb(true,null);})
     .catch(function(e){
       if(e==="gone"){pbSave(fields,cb);return;}
       cb&&cb(false,(e==="auth")?"auth":(e==="error")?"error":"offline");});}

/* ---- drop-in replacements for the GitHub primitives ----
   Same callback contracts, so cloudPull/autoSync/the status dot are untouched. */
function cloudGet(cb){
  if(ownershipAmbiguous()){cb&&cb(null,"error");return;}
  pbGetRecord(function(rec,err){
    if(err){cb&&cb(null,err);return;}
    cb&&cb((rec&&rec.data)||{},null);});}